### PR TITLE
fix(node): `createTable()` should save embeddings, and `mergeInsert` should use them

### LINKED ISSUE #2066: bug(node): mergeInsert and add don't seem to have access to embedding functions.
### LanceDB version

_No response_

### What happened?

See failing test in https://github.com/lancedb/lancedb/pull/2065

### Are there known steps to reproduce?

_No response_

### PR DESCRIPTION
**Pull request by wjones127**
* `createTable()` now saves embeddings in the schema metadata. Previously, it would drop them. (`createEmptyTable()` was already tested and worked.)
* `mergeInsert()` now uses embeddings.

Fixes #2066

### CODE REVIEW

File: nodejs/lancedb/merge.ts [hunk 1]
```diff
@@ -1,13 +1,20 @@
-import { Data, fromDataToBuffer } from "./arrow";
+// SPDX-License-Identifier: Apache-2.0
```
Comment (westonpace) [inline nodejs/lancedb/merge.ts:1]: Hmmm, are we missing SPDX checks?

**Review by westonpace — APPROVED** [review]

File: nodejs/lancedb/merge.ts (hunk 1 above)
Comment (wjones127) [reply nodejs/lancedb/merge.ts:1]: I don't see any license check in our CI jobs. I can copy over the Lance one later today.
