### PR TITLE
fix: limit and offset support paginating through FTS and vector search results

### LINKED ISSUE #2459: offset not working properly with FTS
### LanceDB version

0.19

### What happened?

I'm working on a Tauri application, and I'm really invested in lancedb at this point so I hope to God that this isn't a 'well the rust sdk can't do that' sort of thing, but I can't figure out why this full text search is returning an empty result when there are possibly a few dozen matches.

Here is where I set the index:

```rs
pub async fn set_mdx_note_body_index(db: &Connection) -> FlusterResult<()> {
    let tbl = db
        .open_table(DatabaseTables::MdxNote.to_string())
        .execute()
        .await
        .map_err(|e| {
            println!("Error: {:?}", e);
            FlusterError::FailToCreateIndex
        })?;
    tbl.create_index(
        &["raw_body"],
        lancedb::index::Index::FTS(FtsIndexBuilder {
            with_position: false,
            tokenizer_configs: TokenizerConfig::new(
                "simple".to_string(),
                tantivy::tokenizer::Language::English,
            ),
        }),
    )
    .execute()
    .await
    .map_err(|e| {
        println!("Error: {:?}", e);
        FlusterError::FailToCreateIndex
    })?;
    Ok(())
}
```

I've tried several approaches here with the `FtsIndexBuilder`, and so far none have been successful.

This is where I'm querying the data:

```rs
    pub async fn full_text_search(
        db: &FlusterDb<'_>,
        query: &String,
        pagination: &PaginationProps,
    ) -> FlusterResult<Vec<MdxNoteModel>> {
        let tbl = get_table(db, DatabaseTables::MdxNote).await?;

        let items_batch = tbl
            .query()
            .full_text_search(FullTextSearchQuery::new(query.to_string()))
            .limit(pagination.per_page as usize)
            .offset((pagination.per_page * (pagination.page_number - 1)) as usize)
            .execute()
            .await
            .map_err(|e| {
                println!("Error in MdxNoteEntity.full_text_search: {:?}", e);
                FlusterError::FailToConnect
            })?
            .try_collect::<Vec<_>>()
            .await
            .map_err(|e| {
                println!("Error in MdxNoteEntity.full_text_search: {:?}", e);
                FlusterError::FailToFind
            })?;

        if items_batch.is_empty() {
            return Ok(Vec::new());
        }

        let mut items: Vec<MdxNoteModel> = Vec::new();

        for batch in items_batch.iter() {
            let data: Vec<MdxNoteModel> =
                from_record_batch(batch).map_err(|_| FlusterError::FailToSerialize)?;
            items.extend(data);
        }
        Ok(items)
    }
```

Any help here is hugely appreciated it. This app is a really important piece of something that could turn out to be really impactful, and for that reason it's pretty time sensitive.

Thanks in advance.

### Are there known steps to reproduce?

The app is becoming pretty complex. I'm not sure if there's a single set of steps that I can think of that would reproduce this, but I've included the core pieces of relevant code.

### PR DESCRIPTION
**Pull request by wjones127**
Adds tests to ensure that users can paginate through simple scan, FTS, and vector search results using `limit` and `offset`. 

Tests upstream work: https://github.com/lancedb/lance/pull/4318

Closes #2459

### CODE REVIEW

File: rust/lancedb/src/query.rs [hunk 1]
```diff
@@ -1342,7 +1343,7 @@ mod tests {
         // should only have one batch
         while let Some(batch) = stream.next().await {
             // pre filter should return 10 rows
-            assert!(batch.expect("should be Ok").num_rows() == 9);
+            assert_eq!(batch.expect("should be Ok").num_rows(), 10);
```
Comment (wjones127) [inline rust/lancedb/src/query.rs:1484]: This was a bug in an existing test.
