### PR TITLE
fix(node) Remove mpsc from JS SDK

### LINKED ISSUE #405: NodeJS SDK hangs on index creation
```js
(async () => {

     const vectordb = require('vectordb')
     const db = await vectordb.connect('data/sample-lancedb')

     let data = []
     for (let i = 0; i < 10_000; i++) {
         data.push({vector: Array(1536).fill(i), id: `${i}`, content: "", longId: `${i}`},)
     }
     const table = await db.createTable('my_vectors', data)
     await table.createIndex({ type: 'ivf_pq', column: 'vector', num_partitions: 256, num_sub_vectors: 96 })


     const results_1 = await table
         .search(Array(1536).fill(1.2))
         .limit(2)
         .nprobes(20)
         .refineFactor(10)
         .execute()


     const results_2 = await table
         .search(Array(1536).fill(1.2))
         .where("id != '1141'")
         .execute()


     const results_3 = await table
         .search(Array(1536).fill(1.2))
         .select(["id"])
         .execute()

})();
```
SDK version: Main branch
`await table.createIndex({ type: 'ivf_pq', column: 'vector', num_partitions: 256, num_sub_vectors: 96 })` hangs with no output

### PR DESCRIPTION
**Pull request by gsilvestrin**
- remove &mut operations from Table
- Callers / SDKs are responsible for keeping track of the last version of the Table
   - This matches what we are doing in the Python side
- This allow us to remove the mpsc from Table and make all Table operations non-blocking
- remove close function from js sdk, it was never included as part of a public release
- There is a different approach proposed [here](https://github.com/lancedb/lancedb/issues/397), but I think we need to evolve the design first and integrate in the main rust crate vs being a js-only solution

Close #405

### CODE REVIEW

File: node/src/index.ts [hunk 1]
```diff
@@ -390,7 +384,7 @@ export class LocalTable<T = number[]> implements Table<T> {
    * @param indexParams The parameters of this Index, @see VectorIndexParams.
    */
   async createIndex (indexParams: VectorIndexParams): Promise<any> {
-    return tableCreateVectorIndex.call(this._tbl, indexParams)
+    return tableCreateVectorIndex.call(this._tbl, indexParams).then((newTable: any) => { this._tbl = newTable })
```
Comment (wjones127) [inline node/src/index.ts:387]: Okay so IIUC, how this works is:

```ts
// Initializes table
const table = lance.table(...) 
// Clones the table to perform operation in another thread
const create_index_promise = table.create_index(...) 
// Another clone to perform this operation
const delete = table.delete(...) 
// Either create_index or delete will win and overwrite the table reference
await Promise.all([create_index, delete])
```

This is fine for now, since we'll disallow concurrent writes for the time being. But eventually we probably want a better model for updating the table reference after a mutation, since this is a race condition. I'll see if I can create a method soon to update a dataset to the latest version, which is probably the better way to solve this.

File: rust/vectordb/src/table.rs [hunk 2]
```diff
@@ -187,7 +187,7 @@ impl Table {
     }
 
     /// Create index on the table.
-    pub async fn create_index(&mut self, index_builder: &impl VectorIndexBuilder) -> Result<()> {
+    pub async fn create_index(&self, index_builder: &impl VectorIndexBuilder) -> Result<Table> {
```
Comment (wjones127) [inline rust/vectordb/src/table.rs:190]: If you make this take `&self` instead of `&mut self`, you are making the Rust and the Node API different. Node users get to write:

```ts
await table.delete("id = 42")
```

And their table is updated for them. Rust users would now have to remember to use the returned value:

```rust
let table = table.delete("id = 42").await?;
```

This seems unnecessary. I'd keep the Rust methods using `&mut` and change the `Arc<Table>` in Javascript to be `Table`. `Table` is cheap to clone as-is, so no need for it to be in an `Arc`.

File: rust/ffi/node/src/table.rs [hunk 3]
```diff
@@ -12,82 +12,33 @@
...
-use crate::{get_aws_creds, JsDatabase, runtime};
-
-type TableCallback = Box<dyn FnOnce(&mut vectordb::Table, &Channel, Deferred) + Send>;
+use crate::error::ResultExt;
+use crate::{get_aws_creds, runtime, JsDatabase};
 
-// Wraps a LanceDB table into a channel, allowing concurrent access
 pub(crate) struct JsTable {
-    tx: mpsc::Sender<JsTableMessage>,
+    pub table: Arc<Table>,
```
Comment (wjones127) [inline rust/ffi/node/src/table.rs:29]: As suggested in my other comment, if you don't use an `Arc` here it should be easier to clone and get an owned reference that can be mutated in the Rust API.

```suggestion
    pub table: Table,
```

File: node/src/index.ts (hunk 1 above)
Comment (wjones127) [reply node/src/index.ts:387]: https://github.com/lancedb/lance/issues/1124

**Review by wjones127 — CHANGES_REQUESTED** [review]
The Node API changes seem good but the ones to Rust seem unnecessary. IMO we should be consistent across APIs about mutating table.

**Review by wjones127 — APPROVED** [review]
